#version 450
layout(local_size_x = 64) in;

struct Particle {
    vec3 pos;
    vec3 vel;
    float lifetime;
    float age;
};

layout(std430, binding = 1) writeonly buffer OutParticles {
    Particle outParticles[];
};

layout(std430, binding = 2) buffer Counter {
    uint aliveCount;
};

layout(push_constant) uniform SpawnParams {
    uint spawnCount;
    vec3 emitterPos;
    float life;
} spawn;

uint rand(uint seed) {
    seed ^= seed << 13;
    seed ^= seed >> 17;
    seed ^= seed << 5;
    return seed;
}

void main() {
    uint gid = gl_GlobalInvocationID.x;
    if (gid >= spawn.spawnCount) return;

    Particle p;
    uint seed = gid * 747796405u + 2891336453u;
    float rand01 = float(rand(seed) & 0xFFFFu) / 65535.0;

    p.pos = spawn.emitterPos + vec3(
        (rand01 - 0.5) * 0.2,   // трохи розкидати по X
        0.0,
        (rand01 - 0.5) * 0.2    // трохи по Z
    );

    p.vel = normalize(vec3(
        (float(rand(seed+1) & 0xFFFFu) / 65535.0 - 0.5),
        1.0,
        (float(rand(seed+2) & 0xFFFFu) / 65535.0 - 0.5)
    )) * 2.0;   // швидкість від 2.0 вгору в рандомному напрямку
    p.lifetime = spawn.life;
    p.age = 0;

    uint idx = atomicAdd(aliveCount, 1);
    outParticles[idx] = p;
}
