#version 450
layout(local_size_x = 1) in;

layout(std430, binding = 3) buffer OutCounter {
    uint outAliveCount;
};

layout(std430, binding = 4) buffer IndirectArgs {
    uint vertexCount;
    uint instanceCount;
    uint firstVertex;
    uint firstInstance;
};

layout(push_constant) uniform DrawParams {
    uint vertsPerParticle;
} draw;

void main() {
    vertexCount = draw.vertsPerParticle;
    instanceCount = outAliveCount;
    firstVertex = 0;
    firstInstance = 0;
}
