#version 450
layout(local_size_x = 1) in;

layout(std430, binding = 2) buffer Counter {
    uint aliveCount;
};

layout(std430, binding = 3) buffer IndirectArgs {
    uint vertexCount;
    uint instanceCount;
    uint firstVertex;
    uint firstInstance;
};

layout(push_constant) uniform DrawParams {
    uint vertsPerParticle;
} draw;

void main() {
    vertexCount = aliveCount * draw.vertsPerParticle;
    instanceCount = 1;
    firstVertex = 0;
    firstInstance = 0;
}
